spring:
  application:
    name: ocorrencias-service
  datasource:
    url: jdbc:postgresql://localhost:5432/achadosperdidos?currentSchema=ocorrencias_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

services:
  objetos:
    base-url: ${SERVICES_OBJETOS_BASE_URL:http://localhost:8081}

server:
  port: 8082